---
title: "Summer survey - comparison with MARINe data "
author: "Amelia Ritger"
date: "8/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(lubridate)
```

# RUN THIS AFTER RUNNING "summer-all.Rmd"

MARINe quadrat data
```{r}
marine_quad_raw <- read_csv(here("data","surveys", "marine", "amelia_ritger_cbs_summary_data_20210817-quad.csv")) %>% 
  clean_names() %>% 
    rename("site"="intertidal_sitename") %>%
  select("site","survey_rep","year","species","total_count","density_per_m2")

marine_quad <- marine_quad_raw %>%
  filter(species %in% c("Acanthinucella spp","Cancer antennarius",  "Kelletia kelletii", "Leptasterias spp","Mexacanthina lugubris", "Nucella canaliculata","Nucella emarginata/ostrina","Pachygrapsus crassipes","Pisaster ochraceus","Tegula funebralis")) %>%
  mutate(group_species=ifelse(str_detect(species, pattern="Cancer"), "Crabs",
                            ifelse(str_detect(species, pattern="Pachy"), "Crabs",
                                   ifelse(str_detect(species, pattern="canth"), "Whelks",
                                           ifelse(str_detect(species, pattern="Kell"), "Whelks",
                                                  ifelse(str_detect(species, pattern="ucel"), "Whelks",
                                                         ifelse(str_detect(species, pattern="Lepta"), "Small stars",
                                                                ifelse(str_detect(species, pattern="Pisaster"), "Large stars",species)))))))) %>%
  group_by(site, year, group_species) %>%
  summarize(density_per_m2=sum(density_per_m2)) %>%
  ungroup()

#Get the number of times a site was surveyed
marine_quad_n <- marine_quad %>%
  select(site, year) %>%
  distinct() %>% #get distinct number of site and year combinations
  group_by(site) %>%
  summarize(n=n()) %>%
  ungroup()

#Get the average population densities across all years
marine_quad_avg <- marine_quad %>%
  group_by(site, group_species) %>%
  summarize(mean_density=mean(density_per_m2)) %>%
  ungroup()

#Add the number of times a site was surveyed to average population densities across all years
marine_quad_merge <- full_join(marine_quad_avg, marine_quad_n)
  # rename("Site"="site",
  #        "Species"="group_species",
  #        "Mean density per m2"="mean_density")

sort(unique(marine_quad$species))
sort(unique(marine_quad$site))
```

MARINe swath data 
```{r}
marine_swath_raw <- read_csv(here("data","surveys", "marine", "amelia_ritger_cbs_summary_data_20210817-swath.csv")) %>% 
  clean_names() %>%
  rename("site"="intertidal_sitename") %>%
  select("site","year","species","total_count","density_per_m2")

marine_swath <- marine_swath_raw %>%
  filter(species %in% c("Henricia spp", "Leptasterias spp", "Pisaster giganteus", "Pisaster ochraceus")) %>%
  mutate(group_species=ifelse(str_detect(species, pattern="Lepta"), "Small stars", "Large stars")) %>%
  group_by(site, year, group_species) %>%
  summarize(density_per_m2=sum(density_per_m2)) %>%
  ungroup()

#Get the number of times a site was surveyed
marine_swath_n <- marine_swath %>%
  select(site, year) %>%
  distinct() %>%
  group_by(site) %>%
  summarize(n=n()) %>%
  ungroup()

#Get the average population densities across all years
marine_swath_avg <- marine_swath %>%
  group_by(site, group_species) %>%
  summarize(mean_density=mean(density_per_m2)) %>%
  ungroup()

#Add the number of times a site was surveyed to average population densities across all years
marine_swath_merge <- full_join(marine_swath_avg, marine_swath_n)
```

Missing species (in my surveys, not in MARINe quadrat or swath df):
"Acanthina paucilirata","Cancer branneri", "Cancer jordani", "Cancer oregonensis", "Cancer productus"

Combine MARINe quadrat and swath data
```{r}
marine_merge_sum <- full_join(marine_swath_merge, marine_quad_merge) %>%
  group_by(site, group_species) %>%
  summarize(mean_density=mean(mean_density))

marine_merge <- full_join(marine_merge_sum, marine_swath_n) #Looks like species were picked up on swaths on years where species weren't picked up on quadrats (and never vice versa), so merge with swath n column
```

Now plot MARINe data alongside my data
```{r}
#Join MARINe df with my df
marine_merge <- marine_merge %>%
  rename("location"="site",
         "species"="group_species",
         "density_per_m2"="mean_density") %>%
  mutate(location=ifelse(location=="Bodega", "Bodega Bay", ifelse(location=="Sokol Point; Chilean Memorial", "Sokol Point", location)))

my_data <- read_csv(here("data", "surveys", "grouped_data.csv")) %>%
  mutate(location=ifelse(location=="Cabrillo NM", "Cabrillo III",location))

all_merge <- full_join(marine_merge, my_data) %>%
  mutate(n=ifelse(is.na(n), 1, n), #replace NA values with 1
         survey=ifelse(test=n>1, yes="MARINe", no="Ritger")) %>%
  filter(density_per_m2>0)

#set species order for plotting
all_merge$species <- factor(all_merge$species, levels=c("Tegula funebralis", "Whelks", "Crabs", "Small stars", "Large stars"))

#set site order for plotting
all_merge$location <- factor(all_merge$location, levels=c("Cabrillo III", "Alegria", "Lompoc Landing", "Bodega Bay", "Fogarty Creek", "Sokol Point"))

ggplot(all_merge, aes(x=location, y=density_per_m2, fill=species)) +
  geom_bar(position="dodge", stat="identity") +
  ylab(bquote('Species density ' (per ~m^2))) +
  xlab("Location") +
  theme_bw() +
  facet_wrap(~survey)

ggsave(here("figures", "summer-comp.png"), height=20, width=40, units="cm")
```

