---
title: "June-July sensor data wrangling"
author: "Amelia Ritger"
date: "8/3/2021"
output: html_document
---

# Load packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, messages = FALSE, error = FALSE)

library(tidyverse)
library(janitor)
library(here)
library(lubridate)
library(scales)
library(rvest) #to scrape tide data from the internet
```

## Read in the data
```{r}
jj <- read_csv(here("data","sensors", "sensor-data_all.csv")) %>% 
  clean_names() %>%
  mutate(date_time=mdy_hms(date_time), #aapply lubridate to date/time column
         date=format(date_time, '%m/%d/%Y'), #create only date column
         time=format(date_time, '%H:%M:%S')) %>% #create only time column
 select(site, sensor_number, date_time, date, time, temp_c, p_h) %>%
    mutate(site=replace(site, site=="LOL", "Lompoc Landing"),
           site=replace(site, site=="ALG", "Alegria"),
           site=replace(site, site=="BML", "Bodega Bay")) #rename locations
```

## Plot it up
```{r}
#set site order for plotting (legend)
jj$site <- factor(jj$site, levels=c("Alegria", "Lompoc Landing", "Bodega Bay"))

ggplot(jj, aes(x=date_time, y=p_h, group=site)) +
  geom_line(aes(color=site), size=0.7) +
  geom_point(aes(color=site), size=0.5) +
  scale_x_datetime(breaks = scales::date_breaks("1 week"), 
                    labels = date_format("%m/%d %H:%m")) +
  xlab("Date time") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=90))

ggsave(here("figures", "june-aug.png"), height=20, width=40, units="cm")
```

Plot temp up for good measure
```{r}
ggplot(jj, aes(x=date_time, y=temp_c, group=site)) +
  geom_line(aes(color=site), size=0.7) +
  geom_point(aes(color=site), size=0.5) +
  scale_x_datetime(breaks = scales::date_breaks("1 week"), 
                    labels = date_format("%m/%d %H:%m")) +
  xlab("Date time") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=90))

ggsave(here("figures", "june-aug_temp.png"), height=20, width=40, units="cm")
```

Plot each site, temp and pH 

BML
```{r}
bml <- jj %>%
  filter(site=="Bodega Bay")

ggplot(bml, aes(x=date_time)) +
  geom_line(aes(y=p_h), color="red") + 
  geom_line(aes(y=temp_c), color="blue") + # Divide by 10 to get the same range than the temperature
  scale_y_continuous(name = "pH", #first axis name
    sec.axis = sec_axis(~., name="Temp (C)")) + #second axis name and features
  scale_x_datetime(breaks = scales::date_breaks("1 week"), 
                    labels = date_format("%m/%d %H:%m")) +
  xlab("Date time") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=90))

ggsave(here("figures", "bml?.png"), height=20, width=40, units="cm")

## Try it with pH and temp sorted as "groups"
bml2 <- bml %>%
  pivot_longer(cols=temp_c:p_h,
               names_to = "group",
               values_to = "value")

ggplot(bml2, aes(x=date_time, y=value, group=group)) +
  geom_line(aes(color=group), size=0.7) +
  #geom_point(aes(color=group), size=0.5) +
  scale_x_datetime(breaks = scales::date_breaks("1 week"), 
                    labels = date_format("%m/%d %H:%m")) +
  xlab("Date time") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=90))
```
Let's come back to this...

Add tide cycles!
```{r}
bml_tide <- read_html("http://tbone.biol.sc.edu/tide/tideshow.cgi?tplotdir=horiz;gx=640;gy=240;caltype=ndp;type=mrare;interval=00%3A15;glen=112;fontsize=%2B0;units=feet;year=2021;month=05;day=25;hour=00;min=01;tzone=local;d_year=;d_month=01;d_day=01;d_hour=00;d_min=00;ampm24=24;colortext=black;colordatum=white;colormsl=yellow;colortics=red;colorday=skyblue;colornight=deep-%3Cbr%20%2F%3Eskyblue;colorebb=seagreen;colorflood=blue;site=Gaviota%2C%20California") %>%
  html_elements("pre") %>%
  html_text2()

bml_tide_table <- data.frame(bml_tide) %>%
  mutate(date_tide = str_split(bml_tide, pattern = "\n")) %>%
  unnest(date_tide) %>%
  select(date_tide) %>%
  mutate(date_tide=as.factor(date_tide)) %>%
  separate(date_tide, into = c("date", "space", "time", "time_zone", "tide"), sep="\\s") %>%
  unite("time", "time", "time_zone", sep="\ ") %>%
  select(-"space")

%>%
  separate_rows(date_tide, sep="\\s") %>%
  separate(date_tide, into = c("date", "space", "time", "ds", "tide"), extra = 'merge')
  
```

